def generate_markdown_report(specialist_findings: list):
    lines = []

    lines.append("# RepoPilot Code Analysis Report")
    lines.append("")
    lines.append("Generated by RepoPilot")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(
        f"- Total findings: {len(specialist_findings)}"
    )
    lines.append("")

    # Eğer specialist finding yoksa
    if not specialist_findings:
        lines.append("No meaningful issues found.")
        lines.append("")

        return "\n".join(lines)

    # Specialist sonuçları
    lines.append("## Findings")
    lines.append("")

    for index, finding in enumerate(
        specialist_findings,
        start=1
    ):
        lines.append(
            f"### {index}. [{finding.agent.upper()}] {finding.title}"
        )
        lines.append("")

        lines.append(
            f"- **Severity:** {finding.severity}"
        )
        lines.append("")

        lines.append("**Description**")
        lines.append("")
        lines.append(finding.description)
        lines.append("")

        lines.append("**Suggestion**")
        lines.append("")
        lines.append(finding.suggestion)
        lines.append("")

    return "\n".join(lines)